services:
  postgres:
    image: postgres:16-alpine
    container_name: hrmis_saas_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hrmis_saas
      POSTGRES_USER: hrmis_user
      POSTGRES_PASSWORD: hrmis_password
    ports:
      - "5433:5432"
    volumes:
      - hrmis_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hrmis_user -d hrmis_saas"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  hrmis_postgres_data: