import { act, fireEvent, render, screen } from '@testing-library/react';
import { expect, it, vi } from 'vitest';
import { AuthContext } from '../context/AuthContext.jsx';
import { formDraftApi } from '../api/formDraftApi.js';
import SignatureRequestForm from '../components/documents/SignatureRequestForm.jsx';
vi.mock('../components/documents/SignatureFieldPlacement.jsx', () => ({ default: ({ recipients, onFieldsChange }) => <button type="button" onClick={() => onFieldsChange(1, [{ field_type: 'text', label: 'Job title', x: .2, y: .3, width: .2, height: .05, page_number: 1, required: true }])}>Place field for second signer ({recipients[1]?.fields.length || 0})</button> }));
it('restores multiple signers, roles, order, fields, seal, message and deadline', async () => {
  let saved;
  vi.spyOn(formDraftApi, 'get').mockImplementation(async () => ({ data: saved || {} }));
  vi.spyOn(formDraftApi, 'save').mockImplementation(async (key, payload) => ({ data: saved = { key, ...payload, revision: 1, updated_at: '2026-09-09T09:00:00Z' } }));
  const submit = vi.fn();
  const tree = () => <AuthContext.Provider value={{ user: { id: 'owner' } }}><SignatureRequestForm document={{ id: 'doc-1', title: 'Employment contract', original_filename: 'contract.pdf' }} employees={[{ id: 'employee-1', full_name: 'Amina' }, { id: 'employee-2', full_name: 'Brian' }]} onSubmit={submit} /></AuthContext.Provider>;
  const first = render(tree()); await act(async () => {});
  fireEvent.click(screen.getByText('Add signatory'));
  fireEvent.change(screen.getByLabelText('Signatory 1'), { target: { value: 'employee-1' } });
  fireEvent.change(screen.getByLabelText('Signatory 2'), { target: { value: 'employee-2' } });
  fireEvent.change(screen.getByLabelText('Role for signatory 2'), { target: { value: 'Employer' } });
  fireEvent.change(screen.getAllByLabelText('Sequence')[1], { target: { value: '3' } });
  fireEvent.change(screen.getByLabelText('Message to signatories'), { target: { value: 'Please review carefully' } });
  fireEvent.change(screen.getByLabelText('Completion date'), { target: { value: '2026-12-20' } });
  fireEvent.change(screen.getByLabelText('Deadline time'), { target: { value: '16:30' } });
  fireEvent.click(screen.getByLabelText('Require company seal after signing'));
  fireEvent.click(screen.getByText('Place field for second signer (0)'));
  fireEvent.click(screen.getByText('Save draft'));
  await screen.findByText(/Draft saved/); expect(submit).not.toHaveBeenCalled();
  expect(saved.data.recipients[1]).toMatchObject({ employee_id: 'employee-2', role_label: 'Employer', sequence: '3', fields: [{ field_type: 'text', label: 'Job title' }] });
  first.unmount(); render(tree()); await screen.findByText('Resume draft'); fireEvent.click(screen.getByText('Resume draft'));
  expect(screen.getByLabelText('Signatory 2')).toHaveValue('employee-2');
  expect(screen.getByLabelText('Role for signatory 2')).toHaveValue('Employer');
  expect(screen.getByLabelText('Message to signatories')).toHaveValue('Please review carefully');
  expect(screen.getByLabelText('Completion date')).toHaveValue('2026-12-20');
  expect(screen.getByLabelText('Deadline time')).toHaveValue('16:30');
  expect(screen.getByLabelText('Require company seal after signing')).toBeChecked();
  expect(screen.getByText('Place field for second signer (1)')).toBeVisible();
  vi.restoreAllMocks();
});
